
services:
  - type: web
    name: jojo-plus
    env: python
    plan: free
    buildCommand: |
      python stock_selector.py  # <== 每次部署啟動前執行一次
    startCommand: python server.py

  - type: cron
    name: daily-stock-selector
    env: python
    schedule: "45 0 * * *"  # 台灣時間每日 08:45 執行
    command: python stock_selector.py
